### ISSUE TITLE
facing errors while installing

### ISSUE THREAD

**Issue by tusharnankani** [xypnox/todxpy#38]
Hi @xypnox 

I am facing a bunch of errors while installing `todx`

![image](https://user-images.githubusercontent.com/61280281/103459953-90561500-4d38-11eb-8212-96669d7495f5.png)

![image](https://user-images.githubusercontent.com/61280281/103460016-078ba900-4d39-11eb-8e78-a5b3b2de108f.png)

**Comment by xypnox** [comment]
Please read the error messages, it states that one of the dependencies required: levenshtein, for compilation need the microsoft's Visual studio C++ build tools. Go to the link mentioned in the error message and install the tool required. They try installing again.
